// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson52c08f61DecodeGithubComC0dered273GoMusthaveDiplomaTplInternalModels(in *jlexer.Lexer, out *WithdrawalsDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(WithdrawalsDTO, 0, 1)
			} else {
				*out = WithdrawalsDTO{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 WithdrawalDTO
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson52c08f61EncodeGithubComC0dered273GoMusthaveDiplomaTplInternalModels(out *jwriter.Writer, in WithdrawalsDTO) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v WithdrawalsDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson52c08f61EncodeGithubComC0dered273GoMusthaveDiplomaTplInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WithdrawalsDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson52c08f61EncodeGithubComC0dered273GoMusthaveDiplomaTplInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WithdrawalsDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson52c08f61DecodeGithubComC0dered273GoMusthaveDiplomaTplInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WithdrawalsDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson52c08f61DecodeGithubComC0dered273GoMusthaveDiplomaTplInternalModels(l, v)
}
func easyjson52c08f61DecodeGithubComC0dered273GoMusthaveDiplomaTplInternalModels1(in *jlexer.Lexer, out *WithdrawalDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "order":
			out.OrderID = string(in.String())
		case "sum":
			out.Amount = float64(in.Float64())
		case "processed_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ProcessedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson52c08f61EncodeGithubComC0dered273GoMusthaveDiplomaTplInternalModels1(out *jwriter.Writer, in WithdrawalDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix[1:])
		out.String(string(in.OrderID))
	}
	{
		const prefix string = ",\"sum\":"
		out.RawString(prefix)
		out.Float64(float64(in.Amount))
	}
	{
		const prefix string = ",\"processed_at\":"
		out.RawString(prefix)
		out.Raw((in.ProcessedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WithdrawalDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson52c08f61EncodeGithubComC0dered273GoMusthaveDiplomaTplInternalModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WithdrawalDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson52c08f61EncodeGithubComC0dered273GoMusthaveDiplomaTplInternalModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WithdrawalDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson52c08f61DecodeGithubComC0dered273GoMusthaveDiplomaTplInternalModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WithdrawalDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson52c08f61DecodeGithubComC0dered273GoMusthaveDiplomaTplInternalModels1(l, v)
}
