run_address: "localhost:8080"
accrual_system_address: "localhost:8081"

database:
  connection:
    pgx_options:
      pool_max_conns: 10
      pool_min_conns: 1
      pool_max_conn_idle_time: 60s
      pool_health_check_period: 10s

server:
  name: "gophermart"
  config:
    debug: false
  logger:
    level: "DEBUG"
    caller: true
    format: "pretty"