run_address: "localhost:8080"
accrual_system_address: "localhost:8081"

database:
  connection:
    options:
      max_open_conns: 10
      max_conn_lifetime_time: 120s

server:
  name: "gophermart"
  config:
    debug: false
  logger:
    level: "DEBUG"
    caller: false
    format: "pretty"